<?php

/**
 * @file
 * Main module file.
 */

/**
 * Implements hook_help().
 */
function apple_news_help($path, $arg) {
  switch ($path) {

    case 'admin/help#apple_news':
      return '<p>' . t('Push content to <a href="https://www.apple.com/news/">Apple News</a>.') . '</p>';

  }
}

/**
 * Implements hook_menu().
 */
function apple_news_menu() {
  $items = array();

  $items['admin/config/content/apple_news'] = array(
    'title' => 'Apple News',
    'description' => t('Configure content export to Apple News.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('apple_news_settings_form'),
    'access arguments' => array('administer apple_news'),
    'file' => 'apple_news.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function apple_news_permission() {
  return array(
    'administer apple_news' => array(
      'title' => t('Administer Apple News'),
      'description' => t('Perform administration tasks for Apple News.'),
    ),
    'push content to apple news' => array(
      'title' => t('Push content to Apple News'),
      'description' => '',
    ),
  );
}

/**
 * Converts drupal language code to appropriate Apples News value.
 */
function apple_news_language_code($language_code) {
  // @todo
  return $language_code;
}

