<?php

/**
 * @file
 * Main module file.
 */

/**
 * Implements hook_help().
 */
function apple_news_components_help($path, $arg) {
  switch ($path) {
    case 'admin/help#apple_news':
      return '<p>' . t('Various Apple News components.') . '</p>';
  }
}

/**
 * Implements hook_apple_news_api().
 */
function apple_news_components_apple_news_api() {
  return [
    'api' => 1,
    'destinations' => [
      'header_image' => [
        'class' => 'ApplenewscomponentsDestinationHeaderImage',
        'name' => 'Header Image',
      ],
      'header_image' => [
        'class' => 'ApplenewscomponentsDestinationHeaderGradContainer',
        'name' => 'Header Gradient Container',
      ],
      'pullquote' => [
        'class' => 'ApplenewscomponentsDestinationAnimatedPullQuote',
        'name' => 'Animated Pull Quote',
      ],
      'mosiac' => [
        'class' => 'ApplenewscomponentsDestinationMosaic',
        'name' => 'Mosaic',
      ],
    ],
  ];
}
