<?php

/**
 * @file
 * Main module file.
 */

/**
 * Implements hook_help().
 */
function apple_news_article_help($path, $arg) {
  switch ($path) {

    case 'admin/help#apple_news':
      return '<p>' . t('Push articles to <a href="https://www.apple.com/news/">Apple News</a>.') . '</p>';

  }
}

/**
 * Implements hook_apple_news_api().
 */
function apple_news_article_apple_news_api() {
  return array(
    'api' => 1,
    'exports' => array(
      'article' => array(
        'class' => 'AppleNewsExportArticle',
        'name' => t('Articles'),
        'description' => t('Export articles as defined by default install profile.'),
      ),
    ),
  );
}
