<?php

/**
 * @file
 * Main module file.
 */

/**
 * Implements hook_help().
 */
function apple_news_style1_help($path, $arg) {
  switch ($path) {
    case 'admin/help#apple_news_style1':
      return '<p>' . t('Apple news style 1.') . '</p>';
  }
}

/**
 * Implements hook_apple_news_api().
 */
function apple_news_style1_apple_news_api() {
  return [
    'api' => 1,
    'exports' => [
      'node' => [
        'class' => 'Applenewsstyle1ExportNode',
        'name' => t('Nodes'),
        'description' => t('Configurable node export using style 1.'),
      ],
    ],
    'destinations' => [
      'body' => [
        'class' => 'Applenewsstyle1DestinationBody',
        'name' => 'Body',
      ],
      'header_image' => [
        'class' => 'Applenewsstyle1DestinationHeaderImage',
        'name' => 'Header Image',
      ],
      'header_container' => [
        'class' => 'Applenewsstyle1DestinationHeaderGradContainer',
        'name' => 'Gradient Header with Title, Intro and Credits',
      ],
      'pullquote' => [
        'class' => 'Applenewsstyle1DestinationAnimatedPullQuote',
        'name' => 'Animated Pull Quote',
      ],
      'mosiac' => [
        'class' => 'Applenewsstyle1DestinationMosaic',
        'name' => 'Mosaic',
      ],
    ],
  ];
}
