<?php

/**
 * @file
 * Main module file.
 */

/**
 * Implements hook_applenews_api().
 */
function applenews_example_applenews_api() {
  return [
    'api' => 1,
    'exports' => [
      'node' => [
        'class' => 'ApplenewsexampleExportNode',
        'name' => t('Nodes'),
        'description' => t('Example styled node export.'),
      ],
    ],
    'destinations' => [
      'body' => [
        'class' => 'ApplenewsexampleDestinationBody',
        'name' => 'Body',
      ],
      'header_image' => [
        'class' => 'ApplenewsexampleDestinationHeaderImage',
        'name' => 'Header Image',
      ],
      'header_container' => [
        'class' => 'ApplenewsexampleDestinationHeaderGradContainer',
        'name' => 'Header with Credits',
      ],
      'pullquote' => [
        'class' => 'ApplenewsexampleDestinationPullQuote',
        'name' => 'Pull Quote',
      ],
      'images' => [
        'class' => 'ApplenewsexampleDestinationImages',
        'name' => 'Mosaic/Gallery',
      ],
      'ad' => [
        'class' => 'ApplenewsexampleDestinationAd',
        'name' => 'Banner Ad',
      ],
    ],
  ];
}
